### PR TITLE
Feature/get main page content from backend

### PR DESCRIPTION
**Pull request by fnoori**
Main page meme content coming from db

### CODE REVIEW

**Comment by adnanrh** [comment]
Not sure what we have time to do, but it seems both vote and comment counts are incorrect? I'll take a look at the backend response

**Comment by fnoori** [comment]
> Not sure what we have time to do, but it seems both vote and comment counts are incorrect? I'll take a look at the backend response

yup, not sure exacly what is going on there, but it seems the votes and comments are being counted incorrectly in one of the handlers. I couldn't figure out what exactly.

**Comment by TheKingWizard** [comment]
Why were the props changed from camel case? I think you should change them back because there's a few other places where they're referenced and those references haven't been changed. There seem to be quite a few errors if you look at the client side console

**Comment by fnoori** [comment]
Oh snap, I just realized my mistake.

I though I needed to change them to underscore case because that's how they were coming from the database.

But now I realize that I can just convert everything into ```camelCase``` as ```Index.vue``` gets the memes from the database. This way I won't need to convert everything else into underscore case.

**Review by TheKingWizard — APPROVED** [review]

**Comment by fnoori** [comment]
Main page contents coming from database

**Pull request merged**
